config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope "/admin" do
    resources :users
    get 'auditors' => 'users#auditors'
  end
  resources :standards
  get "proposals/:proposal_id/items/:item_id/schedule", to: "proposals#schedule", as: "schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/confirm_schedule", to: "items#confirm_schedule", as: "confirm_schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/cancel_schedule", to: "items#cancel_schedule", as: "cancel_schedule_proposal_item"
  resources :proposals do
    get "auditors", on: :member
    resources :items

    member do
      get :export
      get :download
    end
  end
  root "home#index"
  resources :companies
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "*path", to: redirect('/')
end

app/views/shared/_companies_search_form.html.erb
<%= search_form_for @q, html: { class: "w-full max-w-sm min-w-[200px]" } do |f| %>
  <div class="relative">
    <%= f.search_field :legal_name_or_sales_name_or_cnpj_cont,
                       class: "w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-28 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow",
                       placeholder: "Name or Cnpj..." %>

    <%= button_tag type: 'submit',
                   class: "absolute top-1 right-1 flex items-center rounded bg-slate-600 py-1 px-2.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#FFFFFF" class="w-4 h-4 mr-2">
        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z" clip-rule="evenodd" />
      </svg>
      Search
    <% end %>
  </div>
<% end %>

app/views/shared/_proposals_search_form.html.erb
<%= search_form_for @q, html: { class: "w-full max-w-sm min-w-[200px]" } do |f| %>
  <div class="relative">
    <%= f.search_field :title_or_status_cont,
                       class: "w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-28 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow",
                       placeholder: "Title or Status..." %>

    <%= button_tag type: 'submit',
                   class: "absolute top-1 right-1 flex items-center rounded bg-slate-600 py-1 px-2.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#FFFFFF" class="w-4 h-4 mr-2">
        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z" clip-rule="evenodd" />
      </svg>
      Search
    <% end %>
  </div>
<% end %>

app/views/shared/_sidenav.html.erb
<nav class="w-1/6 hidden md:flex flex-col text-center p-4 sticky top-20 h-[calc(100vh-80px)]">
  <div class="bg-white shadow-md rounded-lg p-4 mb-6">
    <div class="flex items-center">
      <%= image_tag 'user_avatar.png', alt: "logo", class: 'w-10 h-10 rounded-full border-2 border-gray-200 mr-4' %>
      <div class="text-left flex-1">
        <p class="font-semibold text-sm text-gray-500">Welcome!</p>
        <p class="text-gray-800 text-sm truncate">
          <%= current_user.name %>
        </p>
      </div>
    </div>
  </div>

  <div class="flex-grow">
    <div class=" flex flex-col">


      <%= link_to root_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(root_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
        </svg>
        <span>Home</span>
      <% end %>

      <%= link_to companies_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(companies_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3.75h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Z" />
        </svg>
        <span>Companies</span>
      <% end %>

      <%= link_to proposals_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(proposals_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m3.75 9v7.5m2.25-6.466a9.016 9.016 0 0 0-3.461-.203c-.536.072-.974.478-1.021 1.017a4.559 4.559 0 0 0-.018.402c0 .464.336.844.775.994l2.95 1.012c.44.15.775.53.775.994 0 .136-.006.27-.018.402-.047.539-.485.945-1.021 1.017a9.077 9.077 0 0 1-3.461-.203M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
        </svg>
        <span>Proposals</span>
      <% end %>

      <%= link_to standards_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(standards_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z" />
        </svg>
        <span>Standards</span>
      <% end %>

      <%= link_to auditors_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(auditors_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 14.15v4.25c0 1.094-.787 2.036-1.872 2.18-2.087.277-4.216.42-6.378.42s-4.291-.143-6.378-.42c-1.085-.144-1.872-1.086-1.872-2.18v-4.25m16.5 0a2.18 2.18 0 0 0 .75-1.661V8.706c0-1.081-.768-2.015-1.837-2.175a48.114 48.114 0 0 0-3.413-.387m4.5 8.006c-.194.165-.42.295-.673.38A23.978 23.978 0 0 1 12 15.75c-2.648 0-5.195-.429-7.577-1.22a2.016 2.016 0 0 1-.673-.38m0 0A2.18 2.18 0 0 1 3 12.489V8.706c0-1.081.768-2.015 1.837-2.175a48.111 48.111 0 0 1 3.413-.387m7.5 0V5.25A2.25 2.25 0 0 0 13.5 3h-3a2.25 2.25 0 0 0-2.25 2.25v.894m7.5 0a48.667 48.667 0 0 0-7.5 0M12 12.75h.008v.008H12v-.008Z" />
        </svg>
        <span>Auditors</span>
      <% end %>

      <%= link_to users_path, class: "text-start flex items-center hover:bg-gray-300 focus:ring-1 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-gray-600 dark:hover:bg-gray-300 dark:focus:ring-gray-800 #{current_page?(users_path) ? 'ring-1 ring-gray-300 text-black' : 'text-gray-900 hover:text-black dark:text-gray-400 dark:hover:text-black'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 30 30" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 0 0 3.741-.479 3 3 0 0 0-4.682-2.72m.94 3.198.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0 1 12 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 0 1 6 18.719m12 0a5.971 5.971 0 0 0-.941-3.197m0 0A5.995 5.995 0 0 0 12 12.75a5.995 5.995 0 0 0-5.058 2.772m0 0a3 3 0 0 0-4.681 2.72 8.986 8.986 0 0 0 3.74.477m.94-3.197a5.971 5.971 0 0 0-.94 3.197M15 6.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 3a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Zm-13.5 0a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z" />
        </svg>
        <span>Users</span>
      <% end %>
    </div>
  </div>

  <div class="mt-auto">
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'text-red-500 ring-1 ring-red-500  focus:outline-none hover:bg-red-100 focus:ring-1 focus:ring-red-100 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:text-red dark:border-red-600 dark:hover:text-black dark:hover:bg-red-400 dark:hover:border-red-600 dark:focus:ring-red-100' %>
  </div>
</nav>

app/views/shared/_standards_search_form.html.erb
<%= search_form_for @q, html: { class: "w-full max-w-sm min-w-[200px]" } do |f| %>
  <div class="relative">
    <%= f.search_field :name_cont,
                       class: "w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-28 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow",
                       placeholder: "Name..." %>

    <%= button_tag type: 'submit',
                   class: "absolute top-1 right-1 flex items-center rounded bg-slate-600 py-1 px-2.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#FFFFFF" class="w-4 h-4 mr-2">
        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z" clip-rule="evenodd" />
      </svg>
      Search
    <% end %>
  </div>
<% end %>

app/views/shared/_topnav.html.erb
<nav class="p-4 flex justify-between sticky top-0 h-20 items-center">
  <div class="flex items-center space-x-2">
    <div>
      <%= image_tag 'companhia.png', alt: "logo", class: 'w-10 h-10' %>
    </div>
    <div class="font-bold">
      Audit Tools
    </div>
  </div>
  <div class="flex space-x-2 items-center">
<% unless controller_name == 'sessions' || controller_name == 'passwords' %>
    <% if current_page?(controller: 'companies', action: 'index') %>
        <%= render 'shared/companies_search_form' %>
      <% elsif current_page?(controller: 'proposals', action: 'index') %>
        <%= render 'shared/proposals_search_form' %>
      <% elsif current_page?(controller: 'standards', action: 'index') %>
        <%= render 'shared/standards_search_form' %>
      <% elsif current_page?(controller: 'users', action: 'index') %>
        <%= render 'shared/users_search_form' %>
      <% end %>
  <% end %>
    <div class="md:hidden relative" data-controller="dropdown">
      <button data-action="click->dropdown#toggle" class="focus:outline-none">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>
      <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 py-2 w-48 bg-white rounded-md shadow-xl z-20">
        <%= link_to root_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" do %>
          Home
        <% end %>
        <%= link_to companies_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" do %>
          Companies
        <% end %>
        <%= link_to proposals_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" do %>
          Proposals
        <% end %>
        <%= link_to standards_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" do %>
          Standards
        <% end %>
        <%= link_to users_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-200" do %>
          Users
        <% end %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'block text-red-500 hover:bg-red-100 w-full text-left px-4 py-2' %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_users_search_form.html.erb
<%= search_form_for @q, html: { class: "w-full max-w-sm min-w-[200px]" } do |f| %>
  <div class="relative">
    <%= f.search_field :name_cont,
                       class: "w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-28 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow",
                       placeholder: "Name..." %>

    <%= button_tag type: 'submit',
                   class: "absolute top-1 right-1 flex items-center rounded bg-slate-600 py-1 px-2.5 border border-transparent text-center text-sm text-white transition-all shadow-sm hover:shadow focus:bg-slate-700 focus:shadow-none active:bg-slate-700 hover:bg-slate-700 active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#FFFFFF" class="w-4 h-4 mr-2">
        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z" clip-rule="evenodd" />
      </svg>
      Search
    <% end %>
  </div>
<% end %>