config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope "/admin" do
    resources :users
    get 'auditors' => 'users#auditors'
  end
  resources :standards
  get "proposals/:proposal_id/items/:item_id/schedule", to: "proposals#schedule", as: "schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/confirm_schedule", to: "items#confirm_schedule", as: "confirm_schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/cancel_schedule", to: "items#cancel_schedule", as: "cancel_schedule_proposal_item"
  resources :proposals do
    get "auditors", on: :member
    resources :items

    member do
      get :export
      get :download
    end
  end
  root "home#index"
  resources :companies
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "*path", to: redirect('/')
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :company
  belongs_to :user
  before_save :calc_total_cost

  enum :discount_type, { percentage: 'percentage', fixed: 'fixed' }
  enum :status, { approved: 'Approved', rejected: 'Rejected', onhold: 'On-hold', cancelled: 'Cancelled', client_review: 'Client Review' }

  validates :discount, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :discount_type, inclusion: { in: discount_types.keys }, allow_nil: true

  attribute :status, :string, default: 'On-hold'
  def self.ransackable_attributes(auth_object = nil)
    %w[title status]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def last_updated_at
    return ((Time.now - self.updated_at) / 1.day).to_i if self.items.empty?

    most_recent_item = self.items.max_by(&:updated_at)
    latest_update = [ self.updated_at, most_recent_item.updated_at ].max
    ((Time.now - latest_update) / 1.day).to_i
  end

  def calc_total_cost
    return unless items.present?

    total = items.sum(:total_cost).round(2)

    if discount.present? && discount_type.present?
      case discount_type
      when 'percentage'
        discount_amount = total * (discount.to_f / 100)
        self.total_cost = (total - discount_amount).round(2)
      when 'fixed'
        self.total_cost = [ total - discount.to_f, 0 ].max.round(2)
      else
        self.total_cost = total
      end
    else
      self.total_cost = total
    end
  end

  def display_status
    status_before_type_cast
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_proposal, only: %i[show edit update destroy]
  before_action :set_companies, only: %i[new edit create update]
  before_action :check_items, only: %i[export download]

  # GET /proposals or /proposals.json
  def index
    @q = Proposal.ransack(params[:q])
    @proposals = @q.result(distinct: true)
    @pagy, @proposals = pagy(@proposals)
  end

  def schedule
    @proposal = Proposal.find(params[:proposal_id])
    @item = @proposal.items.find(params[:item_id])
  end

  def auditors
    date = params[:date]
    auditors = get_available_auditors(date)
    render json: auditors
  end

  # GET /proposals/1 or /proposals/1.json
  def show
  end

  def export
    export_response
    redirect_to proposal_url(@proposal), notice: "The proposal export request was successful,
                                                   the company contact will receive it via email."
  end

  def download
    pdf_thread = Thread.new do
      ::Pdfs::PdfDownloaderService.call(@proposal, current_user)
    end

    pdf = pdf_thread.value

    send_data pdf,
              filename: "#{@proposal.title}.pdf",
              type: 'application/pdf',
              disposition: 'attachment'
  end


  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals or /proposals.json
  def create
    @proposal = current_user.proposals.build(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to proposal_url(@proposal), notice: "Proposal was successfully created." }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1 or /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to proposal_url(@proposal), notice: "Proposal was successfully updated." }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1 or /proposals/1.json
  def destroy
    @proposal.destroy!

    respond_to do |format|
      format.html { redirect_to proposals_url, notice: "Proposal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def get_available_auditors(date)
    auditors = User.where(role: 'auditor')
    auditors.select do |auditor|
      !auditor.items.exists?(start_time: date)
    end.map { |auditor| { id: auditor.id, name: auditor.name } }
  end

  def check_items
    redirect_to proposal_url(@proposal), notice: "Could not export, proposal do not have items!" if @proposal.items.empty?
  end

  def export_response
    ::ExportProposalJob.perform_later(@proposal.as_json, current_user.as_json)
  end

  def set_proposal
    @proposal = Proposal.find(params[:id])
  end

  def set_companies
    @companies = Company.by_name
  end

  # Only allow a list of trusted parameters through.
  def proposal_params
    params.require(:proposal).permit(:company_id, :title, :status, :discount, :due_date, :discount_type)
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<div class="container mx-auto px-4 py-8">
  <% if proposal.errors.any? %>
    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-4" role="alert">
      <h2 class="font-bold mb-2"><%= pluralize(proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>
      <ul>
        <% proposal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: proposal, local: true) do |form| %>
    <div class="space-y-6">

      <div class="flex flex-wrap -mx-4">
        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :company_id, "Company", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.collection_select :company_id, @companies, :id, :sales_name, { include_blank: true }, data: { controller: 'slim' }, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>
        </div>

        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :title, "Title", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.text_field :title, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>
        </div>

        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :status, "Status", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.select :status, Proposal.statuses.invert,{ include_blank: true }, data: { controller: 'slim' }, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>
        </div>

        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :due_date, "Payment due date (days)", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.number_field :due_date, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>
        </div>

        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :discount, "Discount", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= form.text_field :discount, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>
        </div>

        <div class="w-full md:w-1/2 px-4 mb-4">
          <%= form.label :discount_type, "Discount Type", class: "block text-gray-700 text-sm font-bold mb-2" %>
          <div class="flex items-center space-x-4">
            <label class="inline-flex items-center">
              <%= form.radio_button :discount_type, 'percentage', class: 'form-radio text-indigo-600 focus:ring-indigo-200' %>
              <span class="ml-2 text-gray-700">Percentage</span>
            </label>
            <label class="inline-flex items-center">
              <%= form.radio_button :discount_type, 'fixed', class: 'form-radio text-indigo-600 focus:ring-indigo-200' %>
              <span class="ml-2 text-gray-700">Fixed</span>
            </label>
          </div>
        </div>
      </div>

      <div class="flex space-x-4">
        <%= link_to "Back to proposals", proposals_path, class: 'default-button' %>

        <%= form.submit "Save Proposal", class: 'success-button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/proposals/_proposal.html.erb
<div id="<%= dom_id proposal %>">
  <p>
    <strong>Company:</strong>
    <%= proposal.company_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= proposal.title %>
  </p>

</div>

app/views/proposals/edit.html.erb
<% content_for :title, "Editing proposal" %>

<%= render "form", proposal: @proposal %>

<br>

app/views/proposals/index.html.erb
<div class="container mx-auto px-4 py-8">
  <% if notice.present? %>
    <p class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4" role="alert"><%= notice %></p>
  <% end %>

  <% content_for :title, "Proposals" %>

  <div class="flex justify-between mb-6">
    <h1 class="text-2xl font-bold">Proposals</h1>
    <%= button_to "New proposal", new_proposal_path, method: :get, class: 'success-button' %>
  </div>

  <div class="space-y-4" id="proposals">
    <% @proposals.each do |proposal| %>
      <div class="bg-white shadow-md rounded-lg p-6 flex justify-between items-center">
        <div class="flex flex-col">
          <p class="text-lg font-semibold mb-2">
            <%= proposal.title %>
          </p>
          <p class="text-sm text-gray-500 mb-1">
            <strong>Company:</strong>
            <%= proposal.company.sales_name %>
          </p>
          <div>
          <span class="self-start text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded me-2 dark:bg-gray-700 dark:text-gray-400 border border-gray-500 ">
            <svg class="w-2.5 h-2.5 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm3.982 13.982a1 1 0 0 1-1.414 0l-3.274-3.274A1.012 1.012 0 0 1 9 10V6a1 1 0 0 1 2 0v3.586l2.982 2.982a1 1 0 0 1 0 1.414Z"/>
            </svg>
            Last edited: <%= proposal.last_updated_at %> days ago
          </span>
            <% if proposal.status.present? %>
              <%= case proposal.status
                  when 'approved'
                    content_tag(:span, proposal.display_status, class: 'self-start bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300')
                  when 'client_review'
                    content_tag(:span, proposal.display_status, class: 'self-start bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300')
                  when 'onhold'
                    content_tag(:span, proposal.display_status, class: 'self-start bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-indigo-900 dark:text-indigo-300')
                  when 'cancelled', 'rejected'
                    content_tag(:span, proposal.display_status, class: 'self-start bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300')
                  else
                    content_tag(:span, 'Unknown Status', class: 'self-start bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300')
                  end %>
            <% end %>
          </div>
        </div>
        <div class="ml-6">
          <%= button_to "Show this proposal", proposal, method: :get, class: 'default-button' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex justify-end mt-6">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
</div>

app/views/proposals/new.html.erb
<% content_for :title, "New proposal" %>

<%= render "form", proposal: @proposal %>

<br>

app/views/proposals/schedule.html.erb
<div data-controller="schedule" data-schedule-proposal-id-value="<%= @proposal.id.to_s %>">
  <% if notice.present? %>
    <p class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4" role="alert"><%= notice %></p>
  <% end %>
  <%= month_calendar(events: @proposal.items) do |date, items| %>
    <% if date.saturday? || date.sunday? %>
      <div class="calendar-day weekend">
        <span class="text-sm text-gray-500"><%= format_date(date) %></span>
        <p class="text-sm text-gray-500">Weekend</p>
      </div>
    <% else %>
      <div class="calendar-day weekday">
        <div>
          <span class="text-sm text-gray-500"><%= format_date(date) %></span>
        </div>
        <%= link_to 'Schedule', '#', data: { action: "schedule#showModal", date: date.iso8601 }, class: 'bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded border border-blue-400' %>
        <% items.each do |audit_item| %>
          <div>
            <u class="text-sm text-gray-800"><%= "#{audit_item.stage} - #{audit_item.user.name if audit_item.user }" %></u>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div data-schedule-target="modal" class="fixed inset-0 overflow-y-auto hidden z-50">
    <div class="fixed inset-0 bg-black bg-opacity-50" data-action="click->schedule#hideModal"></div>

    <div class="flex items-center justify-center min-h-screen p-4">
      <div class="bg-white rounded-lg shadow-lg transform transition-all sm:max-w-lg sm:w-full">
        <button data-action="schedule#hideModal" type="button" class="absolute top-3 right-3 rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 sm:text-sm">
          X
        </button>
        <%= form_with model: [@proposal, @item], url: confirm_schedule_proposal_item_path(@proposal, @item), method: :post, local: true do |form| %>
          <div class="px-6 py-5">
            <h3 class="text-xl leading-6 font-semibold text-gray-900">Scheduling:</h3>
            <p><%= @item.stage %></p>
            <p>Available auditors:</p>
            <%= form.collection_select :user_id, [], :id, :name, { include_blank: true }, data: { controller: 'slim', 'schedule-target': 'auditorSelect' }, class: 'block w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200' %>

            <div class="mt-4">
              <p class="text-sm text-gray-500">
                Scheduling date: <span data-schedule-target="dateDisplay"></span>
              </p>
              <p class="text-sm text-gray-500">
                Confirm and send scheduling confirmation to auditor and company?
              </p>
              <p class="text-sm text-gray-500">
                Company contact: <%= @proposal.company.contact_name %>
              </p>
              <br>
              <% if @item.scheduled? %>
                <hr>
                <br>
                <p class="text-sm text-gray-500">
                  This audit is currently scheduled to: <%= @item.user.name %>
                </p>
                <p class="text-sm text-gray-500">
                  To be executed from: <%= @item.start_time&.strftime("%d/%m/%Y") %> to: <%= @item.end_time&.strftime("%d/%m/%Y") %>.
                </p>
                <br>
                <p class="text-sm text-gray-500">
                  Click on cancel button to cancel the scheduling and notify the auditor.
                </p>
              <% end %>
            </div>
          </div>

          <div class="px-6 py-4 sm:flex sm:flex-row-reverse ">
            <%= form.hidden_field :start_time, data: { schedule_target: "scheduledDateInput" } %>
            <%= form.submit "Confirm", class: "success-button ml-2" %>
        <% end %>
            <% if @item.scheduled? %>
              <%= button_to "Cancel current schedule", cancel_schedule_proposal_item_path(@proposal, @item), method: :post, form_class: "inline", class: "danger-button" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<div class="container mx-auto px-4 py-8" data-controller="proposals">
  <% if notice.present? %>
    <p class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4" role="alert"><%= notice %></p>
  <% end %>

  <% content_for :title, "Proposal Details" %>
  <div class="flex space-x-4 justify-end mb-6">
    <%= link_to "Add Items", new_proposal_item_path(@proposal), data: { turbo_frame: 'item_form' }, class: 'success-button' %>
    <%= link_to "Back to proposals", proposals_path, class: 'default-button' %>
    <%= link_to "Edit this proposal", edit_proposal_path(@proposal), class: 'default-button' %>
    <%= button_to "Destroy this proposal", @proposal, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'danger-button' %>
  </div>

  <div id="<%= dom_id @proposal %>" class="bg-white shadow-md rounded-lg p-6 mb-6 flex justify-between">
    <div>
      <h2 class="text-xl font-bold mb-4">Proposal Details</h2>
      <p class="text-lg font-semibold mb-2">
        <%= @proposal.title %>
      </p>
      <p class="text-sm text-gray-500 mb-2">
        <strong>Company:</strong>
        <%= @proposal.company.sales_name %>
      </p>
      <p class="text-sm text-gray-500 mb-2">
        <strong>Total cost:</strong>
        <%= @proposal.total_cost %>
      </p>
      <% if @proposal.discount.present? %>
        <p class="text-sm text-gray-500 mb-2">
          <strong>Discount:</strong>
          <%= @proposal.discount %><%= @proposal.discount_type == 'percentage' ? '%' : '$' %>
        </p>
      <% end %>
      <p class="text-sm text-gray-500 mb-2">
        <strong>Payment due date:</strong>
        <%= @proposal.due_date %> days
      </p>
      <% if @proposal.status.present? %>
        <p class="text-sm text-gray-500 mb-2">
          <strong>Status:</strong>
          <%= case @proposal.status
              when 'approved'
                content_tag(:span, @proposal.display_status, class: 'self-start bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300')
              when 'client_review'
                content_tag(:span, @proposal.display_status, class: 'self-start bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300')
              when 'onhold'
                content_tag(:span, @proposal.display_status, class: 'self-start bg-indigo-100 text-indigo-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-indigo-900 dark:text-indigo-300')
              when 'cancelled', 'rejected'
                content_tag(:span, @proposal.display_status, class: 'self-start bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300')
              else
                content_tag(:span, 'Unknown Status', class: 'self-start bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300')
              end %>
        </p>
      <% end %>
    </div>
    <div class="relative inline-block text-left">
      <div>
        <button type="button" data-action="proposals#toggleDropdown" class="inline-flex w-full justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
          Export Options
          <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M5.22 8.22a.75.75 0 0 1 1.06 0L10 11.94l3.72-3.72a.75.75 0 1 1 1.06 1.06l-4.25 4.25a.75.75 0 0 1-1.06 0L5.22 9.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>

      <div data-proposals-target="dropdownMenu" class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
        <div class="py-1" role="none">
          <%= link_to "Send to company", "#", data: { action: "proposals#showModal" }, class: 'block text-gray-900 bg-white focus:outline-none hover:bg-gray-100 focus:ring-1 focus:ring-gray-100 font-medium text-sm px-5 py-2.5 mb-2 dark:text-black dark:border-gray-600 dark:hover:bg-gray-100 dark:hover:border-gray-600 dark:focus:ring-gray-100' %>
          <%= link_to "Download", download_proposal_path(@proposal), data: { action: "proposals#timeOutButton", proposals_target: "downloadButton" }, class: 'block text-gray-900 bg-white focus:outline-none hover:bg-gray-100 focus:ring-1 focus:ring-gray-100 font-medium text-sm px-5 py-2.5 mb-2 dark:text-black dark:border-gray-600 dark:hover:bg-gray-100 dark:hover:border-gray-600 dark:focus:ring-gray-100' %>
        </div>
      </div>
    </div>
  </div>

  <div data-proposals-target="modal" class="fixed inset-0 overflow-y-auto hidden z-50">
    <div class="fixed inset-0 bg-black bg-opacity-50" data-action="click->proposals#hideModal"></div>

    <div class="flex items-center justify-center min-h-screen p-4">
      <div class="bg-white rounded-lg shadow-lg transform transition-all sm:max-w-lg sm:w-full">
        <div class="px-6 py-5">
          <h3 class="text-xl leading-6 font-semibold text-gray-900">Confirm send to company?</h3>
          <div class="mt-4">
            <p class="text-sm text-gray-500">This proposal will be sent to the company contact:</p>
            <p class="text-sm text-gray-500"><%= @proposal.company.contact_name %></p>
          </div>
        </div>
        <div class="px-6 py-4 sm:flex sm:flex-row-reverse">
          <%= link_to "Send by Email", export_proposal_path(@proposal, format: :pdf), class: "w-full sm:w-auto inline-flex justify-center rounded-md shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 sm:ml-3 sm:text-sm" %>
          <button data-action="proposals#hideModal" type="button" class="mt-3 sm:mt-0 w-full sm:w-auto inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 sm:text-sm">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>

  <%= turbo_frame_tag 'item_form' do %>
    <% @proposal.items.each do |item| %>
      <div id="<%= dom_id item %>" class="bg-white shadow-md rounded-lg p-6 mb-6">
        <h3 class="text-lg font-semibold mb-4">Item Details</h3>
        <div class="grid grid-cols-2 gap-4 mb-4">
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Standard:</strong>
            <%= item.standard.name %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Stage:</strong>
            <%= item.stage %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Year:</strong>
            <%= item.year %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Onsite man days:</strong>
            <%= item.onsite_man_days %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Off site man days:</strong>
            <%= item.off_site_man_days %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Total days:</strong>
            <%= item.total_days %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Man day rate:</strong>
            <%= item.man_day_rate %>
          </p>
          <p class="text-sm text-gray-700">
            <strong class="font-medium">Total cost:</strong>
            <%= item.total_cost %>
          </p>
        </div>
        <hr>
        <br>
        <p class="text-sm text-gray-700">
          <strong class="font-medium">Scheduling status:</strong>
          <% if item.scheduled? %>
           <%= content_tag(:span, "Scheduled", class: 'self-start bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300') %>
          <% else %>
            <%= content_tag(:span, "Pending schedule", class: 'self-start bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300') %>
          <% end %>
        </p>
        <p class="text-sm text-gray-700">
          <%= "from: " + item.start_time.strftime('%d/%m/%Y') if item.start_time.present? %>
          <%= "to: " + item.end_time.strftime('%d/%m/%Y') if item.end_time.present? %>
        </p>
        <p class="text-sm text-gray-700">
          Auditor: <%= item.user.name if item.user.present? %>
        </p>
        <% if @proposal.status == 'approved' && item.not_scheduled? %>
          <div class="flex justify-end space-x-4">
            <%= link_to "Schedule", schedule_proposal_item_path(@proposal, item), data: { turbo: false }, class: 'default-button' %>
          </div>
        <% elsif @proposal.status == 'approved' && item.scheduled? %>
          <div class="flex justify-end space-x-4">
            <%= link_to "Edit Schedule", schedule_proposal_item_path(@proposal, item), data: { turbo: false }, class: 'default-button' %>
          </div>
        <% else %>
          <div class="flex justify-end space-x-4">
            <%= link_to "Edit", edit_proposal_item_path(@proposal, item), class: 'default-button' %>
            <%= button_to "Destroy", proposal_item_path(@proposal, item), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'danger-button' %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= link_to "Add Items", new_proposal_item_path(@proposal), data: { turbo_frame: 'item_form' }, class: 'success-button' %>
  <% end %>
</div>