config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope "/admin" do
    resources :users
    get 'auditors' => 'users#auditors'
  end
  resources :standards
  get "proposals/:proposal_id/items/:item_id/schedule", to: "proposals#schedule", as: "schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/confirm_schedule", to: "items#confirm_schedule", as: "confirm_schedule_proposal_item"
  post "proposals/:proposal_id/items/:id/cancel_schedule", to: "items#cancel_schedule", as: "cancel_schedule_proposal_item"
  resources :proposals do
    get "auditors", on: :member
    resources :items

    member do
      get :export
      get :download
    end
  end
  root "home#index"
  resources :companies
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "*path", to: redirect('/')
end

app/models/standard.rb
class Standard < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :items, dependent: :restrict_with_exception
  scope :by_name, -> { order(name: :asc) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  load_and_authorize_resource
  before_action :set_standard, only: %i[ show edit update destroy ]

  # GET /standards or /standards.json
  def index
    @q = Standard.ransack(params[:q])
    @standards = @q.result(distinct: true)
    @pagy, @standards = pagy(@standards)
  end

  # GET /standards/1 or /standards/1.json
  def show
  end

  # GET /standards/new
  def new
    @standard = Standard.new
  end

  # GET /standards/1/edit
  def edit
  end

  # POST /standards or /standards.json
  def create
    @standard = Standard.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to standard_url(@standard), notice: "Standard was successfully created." }
        format.json { render :show, status: :created, location: @standard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standards/1 or /standards/1.json
  def update
    respond_to do |format|
      if @standard.update(standard_params)
        format.html { redirect_to standard_url(@standard), notice: "Standard was successfully updated." }
        format.json { render :show, status: :ok, location: @standard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1 or /standards/1.json
  def destroy
    @standard.destroy!

    respond_to do |format|
      format.html { redirect_to standards_url, notice: "Standard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard
      @standard = Standard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def standard_params
      params.require(:standard).permit(:name)
    end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/_form.html.erb
<%= form_with(model: standard, class: "w-full mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4") do |form| %>
  <% if standard.errors.any? %>
    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-4" role="alert">
      <h2 class="font-bold mb-2"><%= pluralize(standard.errors.count, "error") %> prohibited this standard from being saved:</h2>
      <ul class="list-disc list-inside">
        <% standard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full md:w-1/2 px-4 mb-4">
    <%= form.label :name, "Name", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
  </div>

  <div class="flex items-center w-full md:w-1/2 px-4 mb-4">
    <%= link_to "Cancel", standards_path, class: 'default-button' %>
    <%= form.submit "Save standard", class: 'success-button' %>
  </div>
<% end %>

app/views/standards/_standard.html.erb
<div id="<%= dom_id standard %>">
  <p>
    <strong>Name:</strong>
    <%= standard.name %>
  </p>

</div>

app/views/standards/edit.html.erb
<% content_for :title, "Editing standard" %>

<%= render "form", standard: @standard %>

app/views/standards/index.html.erb
<div class="container mx-auto px-4 py-8">
  <% if notice.present? %>
    <p class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4" role="alert"><%= notice %></p>
  <% end %>

  <% content_for :title, "Standards" %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-bold">Standards List</h1>
    <%= button_to "New standard", new_standard_path, method: :get, class: 'success-button' %>
  </div>

  <div class="space-y-4">
    <% @standards.each do |standard| %>
      <div class="bg-white shadow-md rounded-lg p-6 flex justify-between items-center">
        <div>
          <h2 class="text-lg font-semibold mb-2"><%= standard.name %></h2>
        </div>

        <div class="ml-6">
          <%= button_to "Show this standard", standard, method: :get, class: 'default-button' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex justify-end mt-6">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
</div>

app/views/standards/new.html.erb
<% content_for :title, "New standard" %>

<%= render "form", standard: @standard %>

app/views/standards/show.html.erb
<div class="container mx-auto px-4 py-8">
  <% if notice.present? %>
    <p class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4" role="alert"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-bold">Standard Details</h1>
    <div class="flex justify-end space-x-4 mt-6">
      <%= button_to "Back to standards", standards_path, method: :get, class: 'default-button' %>
      <%= button_to "Edit this standard", edit_standard_path(@standard), method: :get, class: 'default-button' %>
      <%= button_to "Destroy this standard", @standard, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'danger-button' %>
    </div>
  </div>

  <div class="bg-white shadow-md rounded-lg p-6">
    <div class="mb-4">
      <h2 class="text-lg font-semibold mb-2">Standard Name</h2>
      <p class="text-gray-700"><strong>Name:</strong> <%= @standard.name %></p>
    </div>
  </div>
</div>